from __future__ import annotations

# 专家组三层图谱的系统导入契约。2.1 只在 2.0 之上增加 Stage 一级主题和
# 双语字段; 训练场景、评价量规、学习内容等既有模块继续沿用原有边界。
V21_SHEET_HEADERS: dict[str, tuple[str, ...]] = {
    "Stages": (
        "StageID",
        "Sequence",
        "StageNameZH",
        "StageNameEN",
        "ShortNameZH",
        "DescriptionZH",
        "DescriptionEN",
        "OBETeachingOutcomeZH",
        "OBETeachingOutcomeEN",
    ),
    "Scenarios": (
        "ScenarioID",
        "StageID",
        "ScenarioName",
        "Background_KeyConstraints",
        "CourseUnit",
        "TrainingMode",
        "StudentRole",
        "CounterpartyRole",
        "StudentTask",
        "CoreOutcome",
        "EstimatedMinutes",
        "Difficulty",
        "ShortNameZH",
    ),
    "Phenomena": (
        "PhenomenonID",
        "StageID",
        "PhenomenonNameZH",
        "PhenomenonNameEN",
        "DescriptionZH",
        "DescriptionEN",
        "Risk",
        "Frequency",
        "ShortNameZH",
    ),
    "KnowledgeResources": (
        "ResourceID",
        "Category",
        "ResourceNameZH",
        "ResourceNameEN",
        "DefinitionZH",
        "DefinitionEN",
        "HomeStageID",
        "LearningRequirement",
        "DisplayTiming",
        "ShortNameZH",
    ),
    "NegotiationStrategies": (
        "StrategyID",
        "StrategyNameZH",
        "StrategyNameEN",
        "DefinitionZH",
        "DefinitionEN",
        "HomeStageID",
        "ApplicableConditions",
        "RecommendedActions",
        "RelatedPhenomenonIDs",
        "ExampleExpression",
        "DiscouragedActions",
        "ExpectedImpact",
        "ShortNameZH",
    ),
    "GraphRelations(Edges)": (
        "SourceID",
        "RelationType",
        "TargetID",
        "AddressingNoteZH",
        "AddressingNoteEN",
    ),
    "Scaffolds": (
        "ScaffoldID",
        "PhenomenonID",
        "Trigger",
        "Level",
        "Format",
        "Content",
        "WithdrawalCondition",
        "MaxUses",
    ),
    "Rubrics": (
        "RubricID",
        "ScenarioID",
        "DimensionName",
        "WeightPercent",
        "Focus",
        "BelowStandard",
        "MeetsStandard",
        "Excellent",
        "EvidenceRequired",
        "PerRound",
    ),
    "Outcomes": (
        "OutcomeID",
        "ScenarioID",
        "ResultCategory",
        "PossibleOutcome",
        "Condition",
        "Ideal",
        "ReflectionQuestion",
        "NextPractice",
    ),
    "LearningContent": (
        "NodeID",
        "NodeType",
        "Title",
        "Summary",
        "MarkdownContent",
        "ContentStatus",
    ),
}

V21_REQUIRED_COLUMNS: dict[str, tuple[str, ...]] = {
    "Stages": (
        "StageID",
        "Sequence",
        "StageNameZH",
        "StageNameEN",
        "DescriptionZH",
        "OBETeachingOutcomeZH",
    ),
    "Scenarios": (
        "ScenarioID",
        "StageID",
        "ScenarioName",
        "CourseUnit",
        "TrainingMode",
        "StudentTask",
    ),
    "Phenomena": (
        "PhenomenonID",
        "StageID",
        "PhenomenonNameZH",
        "PhenomenonNameEN",
        "DescriptionZH",
    ),
    "KnowledgeResources": (
        "ResourceID",
        "Category",
        "ResourceNameZH",
        "ResourceNameEN",
        "DefinitionZH",
    ),
    "NegotiationStrategies": (
        "StrategyID",
        "StrategyNameZH",
        "StrategyNameEN",
        "DefinitionZH",
        "ApplicableConditions",
        "RecommendedActions",
    ),
    "GraphRelations(Edges)": ("SourceID", "RelationType", "TargetID"),
    "Scaffolds": ("ScaffoldID", "PhenomenonID", "Trigger", "Level", "Content"),
    "Rubrics": ("RubricID", "ScenarioID", "DimensionName", "WeightPercent", "Focus"),
    "Outcomes": ("OutcomeID", "ScenarioID", "PossibleOutcome", "Condition"),
    "LearningContent": ("NodeID", "NodeType", "Title", "MarkdownContent", "ContentStatus"),
}

V21_ID_COLUMNS: dict[str, str] = {
    "Stages": "StageID",
    "Scenarios": "ScenarioID",
    "Phenomena": "PhenomenonID",
    "KnowledgeResources": "ResourceID",
    "NegotiationStrategies": "StrategyID",
    "Scaffolds": "ScaffoldID",
    "Rubrics": "RubricID",
    "Outcomes": "OutcomeID",
    "LearningContent": "NodeID",
}
