from __future__ import annotations

# 场景属于平台课程映射, 不属于专家事实表。这里只保存稳定绑定所需的最小字段;
# 教学任务、角色、量规仍由 curriculum/training/assessment 模块负责。
V3_SCENARIOS: tuple[dict[str, str], ...] = (
    {
        "id": "S01",
        "stage_id": "S1",
        "title": "初次接触：索取目录",
        "unit": "初次接触：索取目录",
        "mode": "商务邮件",
    },
    {
        "id": "S02",
        "stage_id": "S1",
        "title": "发出具体询盘",
        "unit": "发出具体询盘",
        "mode": "商务邮件",
    },
    {
        "id": "S03",
        "stage_id": "S1",
        "title": "催询与条件探询",
        "unit": "催询与条件探询",
        "mode": "商务邮件",
    },
    {
        "id": "S04",
        "stage_id": "S2",
        "title": "识别虚盘并催实盘",
        "unit": "应对虚盘",
        "mode": "谈判对话",
    },
    {
        "id": "S05",
        "stage_id": "S2",
        "title": "审核实盘条款",
        "unit": "接收实盘并理解其约束力",
        "mode": "谈判对话",
    },
    {
        "id": "S06",
        "stage_id": "S3",
        "title": "价格还盘攻防",
        "unit": "价格还盘攻防",
        "mode": "谈判对话",
    },
    {
        "id": "S07",
        "stage_id": "S3",
        "title": "付款与交期磋商",
        "unit": "多维度磋商：付款与交期还盘",
        "mode": "谈判对话",
    },
    {
        "id": "S08",
        "stage_id": "S3",
        "title": "有条件接受与成交",
        "unit": "终局博弈：有条件接受、反建议与成交",
        "mode": "谈判对话",
    },
    {
        "id": "S09",
        "stage_id": "S4",
        "title": "确认成交",
        "unit": "确认成交与拟备销售确认书",
        "mode": "商务邮件",
    },
    {
        "id": "S10",
        "stage_id": "S4",
        "title": "催开信用证",
        "unit": "催开信用证",
        "mode": "商务邮件",
    },
    {
        "id": "S11",
        "stage_id": "S5",
        "title": "包装与唛头磋商",
        "unit": "包装与唛头磋商",
        "mode": "谈判对话",
    },
    {
        "id": "S12",
        "stage_id": "S5",
        "title": "分批转船与催装",
        "unit": "分批/转船磋商与催装",
        "mode": "谈判对话",
    },
    {
        "id": "S13",
        "stage_id": "S6",
        "title": "信用证审核改证",
        "unit": "信用证审核与改证",
        "mode": "单证审阅",
    },
    {
        "id": "S14",
        "stage_id": "S6",
        "title": "交单结汇与装运通知",
        "unit": "交单结汇与装运通知",
        "mode": "商务邮件",
    },
    {
        "id": "S15",
        "stage_id": "S7",
        "title": "检验条款磋商",
        "unit": "检验条款磋商",
        "mode": "谈判对话",
    },
    {
        "id": "S16",
        "stage_id": "S8",
        "title": "保险险别磋商",
        "unit": "投保险别磋商",
        "mode": "谈判对话",
    },
    {
        "id": "S17",
        "stage_id": "S8",
        "title": "仲裁条款磋商",
        "unit": "仲裁条款磋商",
        "mode": "谈判对话",
    },
    {
        "id": "S18",
        "stage_id": "S9",
        "title": "提出质量索赔",
        "unit": "提出质量索赔",
        "mode": "商务邮件",
    },
    {
        "id": "S19",
        "stage_id": "S9",
        "title": "应对卖方抗辩",
        "unit": "应对抗辩，证据反驳",
        "mode": "谈判对话",
    },
    {"id": "S20", "stage_id": "S9", "title": "理赔和解", "unit": "理赔和解", "mode": "谈判对话"},
)
